name: get_journal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  bottom_bar: ^1.3.0+1
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bounce: ^1.1.0
  flutter_swipe_button: ^1.1.0
  google_fonts: ^2.3.1
  google_sign_in: ^5.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
